### ISSUE TITLE
Add "\n" after data

### ISSUE THREAD

**Issue by wedneyyuri** [alcacoop/elasticsearch-scroll-stream#12]
Hi, what do you think about adding a "\n" after every object? It will not make the json invalid.

In my case, I need to save the stream to a file but it's really hard to split the line for processing.

**Comment by wedneyyuri** [comment]
Affected line: https://github.com/alcacoop/elasticsearch-scroll-stream/blob/fabee12401660d7109a541da3bbce9cf6c08fa80/lib/elasticsearch-stream.js#L66

**Comment by francov** [comment]
If you want JSON output you have to pass `stream_ops` to the constructor of `ElasticsearchScrollStream` to set `objectMode: true` because the default is `false`. Here the definition:
https://github.com/alcacoop/elasticsearch-scroll-stream/blob/69e6476852c49216c24e774688b0583fdb59db09/lib/elasticsearch-stream.js#L21

You have four parameters, like so:
```
var es_stream = new ElasticsearchScrollStream(client, {<your_query_opts>}, [], {objectMode: true});
```

**Comment by wedneyyuri** [comment]
Hi @francov, I don't think the JSON output is the best solution in this case.

Currently it's working with a [Transform stream](https://nodejs.org/api/stream.html#stream_class_stream_transform) which adds a `\n` after every string. 

It's just a suggestion for improvement, I'm guessing what's the point of pushing an stringified object without a '\n' since we can't pipe to a file and split later?
