### ISSUE TITLE
when using field, and optional _id field, if missing field, error cant set undefined

### ISSUE THREAD

**Issue by teebu** [alcacoop/elasticsearch-scroll-stream#7]
when using scan with fields:['field'], optional '_id' field, can't be set and errors if that field is missing from results. 

```
[ 'TypeError: Cannot set property \'_id\' of undefined',
     '    at node_modules\\elasticsearch-scroll-stream\\lib\\elasticsearch-stream.js:58:28',
```

Solution: use ` _source` instead of `fields`.

**Comment by francov** [comment]
I think this problem is related to relevant changes in the elasticsearch api... see this [https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_search_changes.html#_literal_fields_literal_parameter](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_search_changes.html#_literal_fields_literal_parameter).

As `fields` does not extract `_source` properties anymore.
I'll update the README and close this issue.
Thank you!
